<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>571f6db8-b81e-4346-83d4-c69d816c75ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-main.main-register</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9fcc0a0e-01b3-48a1-b27a-f69f1274b351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-main main-register</value>
      <webElementGuid>eac411e2-266a-4eb5-af0a-efd55ddd7cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/register</value>
      <webElementGuid>b16e396f-fb4e-4c54-b712-50e324698a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>34f0e273-2dc2-4081-b2e1-e1c1f4089eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b0c46056-5ade-456b-a47d-570e9ad26ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>စာရင္းသြင္းရန္</value>
      <webElementGuid>8d350293-9eb9-4e02-97cd-acc27291b2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topLayer&quot;)/div[@class=&quot;side-menu text-center&quot;]/div[@class=&quot;group-btn-login&quot;]/div[@class=&quot;logged-in text-center&quot;]/a[@class=&quot;btn btn-main main-register&quot;]</value>
      <webElementGuid>73f81f65-38e3-4cf4-ac99-2e7118aa625c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@type='button']</value>
      <webElementGuid>2dc206e0-56ce-4de9-8da4-b957c5899fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topLayer']/div/div/div[2]/a</value>
      <webElementGuid>1e02e7f5-0e38-4a0f-b946-4fc122bdbcd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'စာရင္းသြင္းရန္')]</value>
      <webElementGuid>2e32b733-f3bb-4a96-bb35-6c0e29ccb519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ေလာ့အင္'])[1]/following::a[1]</value>
      <webElementGuid>6cab919d-2bef-4662-8f10-985e4fa54677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='စေလာ့ဒ္ဂိမ္း'])[1]/preceding::a[1]</value>
      <webElementGuid>805c872b-a278-4088-8e0c-a32258455401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ဗီဒီယိုဂိမ်းများ'])[1]/preceding::a[2]</value>
      <webElementGuid>da8d1969-7c6f-46d8-a935-94fcb98ef6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='စာရင္းသြင္းရန္']/parent::*</value>
      <webElementGuid>7f3e8cb3-707a-49dd-b0a9-8250744e1d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/register')]</value>
      <webElementGuid>da9fde33-0455-4acf-b379-b39a2c0b4419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/a</value>
      <webElementGuid>61e03132-6e88-451f-9197-1e8ab806e1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/register' and @type = 'button' and (text() = 'စာရင္းသြင္းရန္' or . = 'စာရင္းသြင္းရန္')]</value>
      <webElementGuid>6f1f78b0-9b8e-42dd-a99c-e585423c7bb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
