<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Referral id must be correct and exist_c115e2</name>
   <tag></tag>
   <elementGuidId>4ce9f5f8-91ac-4075-907c-0aed07b48fb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='referral_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;referral_id&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9aa470df-e6ba-4140-bbb2-0d220c615aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c12810f-35e0-455f-995c-9378d4a9660d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-box input-lg full-width disabledrag ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern ng-valid-maxlength</value>
      <webElementGuid>e8673343-43f2-49cc-a4c0-228fd1a07f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>referral_id</value>
      <webElementGuid>258b6aab-1dba-4cec-8118-531941decf5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>dataRegister.referral_id</value>
      <webElementGuid>3b4b0a88-6ef2-49f7-adf3-bba90f62886f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern-restrict</name>
      <type>Main</type>
      <value>^[0-9a-zA-Z ]*$</value>
      <webElementGuid>636a512e-70bc-4b01-9fd1-2d5134b62bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>9ad86c21-e4b0-485a-87b5-f9c15aeddaaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fb2e9ddc-1a01-41b3-8622-3c847be8fc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>မိတ္ဆက္ေပးသူဂိမ္းအေကာင့္</value>
      <webElementGuid>2019684b-34be-457d-b324-91dfde6f1755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>onFocusCheckReferralExist()</value>
      <webElementGuid>886ae3d2-252a-4e8d-bca0-b6136e324ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>inputReferralAction.isFocus = true</value>
      <webElementGuid>d24135c7-bfc0-420f-8fdb-cd31b783c236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>outFocusCheckReferralExist();inputReferralAction.isFocus = false</value>
      <webElementGuid>a83cf726-803c-4b39-bcf8-8ccfe4886a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>disableReferralForRid ? disableReferralForRid : checkOtpTime</value>
      <webElementGuid>c30d4065-421c-4ca8-b208-d14aebf8fed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'disable' : disableReferralForRid ? disableReferralForRid : checkOtpTime }</value>
      <webElementGuid>289e4cbb-aba8-46f6-a3a7-49511f74a314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register-mobile&quot;)/div[@class=&quot;register-wrapper&quot;]/form[@class=&quot;ok-yg ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-minlength ng-dirty ng-valid-parse ng-valid-pattern&quot;]/div[@class=&quot;row&quot;]/input[@class=&quot;input-box input-lg full-width disabledrag ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern ng-valid-maxlength&quot;]</value>
      <webElementGuid>58b4c0e7-0845-40cc-9902-3680f49be211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/register/Page_YG168  Best Online Casino In Myanmar/iframe__registerFrame</value>
      <webElementGuid>95eabefa-2fa5-4fe2-b486-a7b4d1f9a173</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='referral_id']</value>
      <webElementGuid>6317da84-0807-4f43-b365-163d24442422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register-mobile']/div/form/div[6]/input</value>
      <webElementGuid>80c51c32-aa78-4b46-8bd0-de525a39c99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>85f8a16e-f23a-4143-aff2-8fa6bb72beb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'referral_id' and @placeholder = 'မိတ္ဆက္ေပးသူဂိမ္းအေကာင့္']</value>
      <webElementGuid>3bcbc9a6-0b3e-4b93-b8f6-311e6e2945aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
