<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OTP verification_captcha</name>
   <tag></tag>
   <elementGuidId>a94fcc8f-97d0-47e9-b199-5b2f3d06dd1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='captcha']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;captcha&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>333f293c-f7a5-4c5f-9140-7cd830f7dfcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7362d2e9-e316-4e30-a1d0-053a76cc5b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>captcha</value>
      <webElementGuid>d40c2498-b737-4e1a-8290-a363e870c0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>နံပတ္ကုဒ္</value>
      <webElementGuid>ff16c0d3-2b57-494a-8370-4d3f39dceacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>0fafe9cc-d3bf-4bb4-9d98-9948e955baf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>dfb377b3-da5d-47d4-a792-50b70d30a176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern-restrict</name>
      <type>Main</type>
      <value>^[0-9]*$</value>
      <webElementGuid>f89aad0c-1495-496e-b049-29d25741db00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5f88fe61-db56-43ff-8688-7a367c751599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>otpData.captcha</value>
      <webElementGuid>c57d83cd-e785-4348-bfc0-2d26926c8d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-box ng-pristine ng-untouched ng-valid ng-empty ng-valid-minlength ng-valid-maxlength ng-dirty-add ng-valid-parse-add ng-animate ng-pristine-remove</value>
      <webElementGuid>7119cd33-e364-44e1-ace0-2a4a6469cc6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>87a638c4-0f6f-49aa-842b-ed08f896c8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;platform-ios content-only desktop grade-a platform-browser platform-win32 platform-ready popup-open&quot;]/div[@class=&quot;popup-container v2-theme-popup otp-popup popup-showing active&quot;]/div[@class=&quot;popup&quot;]/div[@class=&quot;popup-body&quot;]/div[@class=&quot;modal-select-otp&quot;]/div[@class=&quot;row&quot;]/input[@class=&quot;form-control input-box ng-pristine ng-untouched ng-valid ng-empty ng-valid-minlength ng-valid-maxlength ng-dirty-add ng-valid-parse-add ng-animate ng-pristine-remove&quot;]</value>
      <webElementGuid>64cb3f18-7b13-49d3-8ac2-615abe59f545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/register/Page_YG168  Best Online Casino In Myanmar/iframe__registerFrame</value>
      <webElementGuid>ef00e16c-4e59-44ef-80ec-bf0cb58c2e9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='captcha']</value>
      <webElementGuid>00bff4cc-8d1c-40c1-84f9-75095923b838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>5c1d8374-28c2-4589-bfc2-da487ab1778a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'captcha' and @placeholder = 'နံပတ္ကုဒ္']</value>
      <webElementGuid>d271f6fc-4b2d-4875-9753-035d68ef0e9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
