<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>2a3343b5-7b4d-405c-a82b-682c5d0a3f9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu-video-game-icon']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-video-game-icon > div.card > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ce628522-f31e-4bbd-9fdb-2188a4c4584c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.santalong.com/background/fish_gamehall.webp</value>
      <webElementGuid>867727ec-dcd3-4b2b-8ec5-94094789fed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-video-game-icon&quot;)/div[@class=&quot;card&quot;]/img[1]</value>
      <webElementGuid>73ada8e3-13b2-4fdd-b647-8a7cfb17062e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menu-video-game-icon']/div/img</value>
      <webElementGuid>ad33a25a-3d80-4f05-b8f0-4754f65acd21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.santalong.com/background/fish_gamehall.webp')]</value>
      <webElementGuid>4c44b5ee-bd05-4040-87ba-d0c56e3382ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/div/img</value>
      <webElementGuid>ad86a0eb-cbbe-43a3-9438-d2a36f2a7d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.santalong.com/background/fish_gamehall.webp']</value>
      <webElementGuid>b328bbc2-107a-485d-9689-92cf41f37dc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
