<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_live_full-width</name>
   <tag></tag>
   <elementGuidId>28b8fb06-6947-430b-883c-ad00b53baccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topGameTabs']/div/div[4]/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.item-game.poker > div.app-card-wrapper.wrapper > a > div.card > img.full-width</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>abb26d09-6563-4a52-885b-749f46ac74d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-width</value>
      <webElementGuid>d7b2feb8-90ca-4148-8ee4-6db400488ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.santalong.com/background/pk89_gamehall.webp</value>
      <webElementGuid>bbf9d2c9-580e-4ba4-89de-68fa2e3f2916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topGameTabs&quot;)/div[@class=&quot;wrapper-games-tab&quot;]/div[@class=&quot;item-game poker&quot;]/div[@class=&quot;app-card-wrapper wrapper&quot;]/a[1]/div[@class=&quot;card&quot;]/img[@class=&quot;full-width&quot;]</value>
      <webElementGuid>c535aba1-99fb-48f6-b25f-0c74471786ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topGameTabs']/div/div[4]/div/a/div/img</value>
      <webElementGuid>855cadb6-ca23-4451-ba00-6551113f8a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.santalong.com/background/pk89_gamehall.webp')]</value>
      <webElementGuid>3110f6e4-eeae-40af-914f-35e80c3301b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a/div/img</value>
      <webElementGuid>bbd0a13a-21b1-4d2a-bf35-bc22206d61aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.santalong.com/background/pk89_gamehall.webp']</value>
      <webElementGuid>47208768-86f4-4180-9088-0fa2a753605f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
