<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>67b5255a-8769-4ba0-9737-ff65f176ec2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu-slot-icon']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>eb91543c-0a79-4632-a4a1-701f0adcd4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.santalong.com/background/slot_gamehall.webp</value>
      <webElementGuid>a889df35-9ba1-44c8-a861-122ca7d856e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-slot-icon&quot;)/div[@class=&quot;card&quot;]/img[1]</value>
      <webElementGuid>146b399c-ed0d-4965-b269-b95ac8b1f584</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menu-slot-icon']/div/img</value>
      <webElementGuid>e9c6a86c-ab8e-4fdc-8bde-8e3fca0869ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.santalong.com/background/slot_gamehall.webp')]</value>
      <webElementGuid>2a84ef4d-e477-4547-ab72-df90da7d7c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>c988c372-a8a5-499f-a220-c0569ac8c941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.santalong.com/background/slot_gamehall.webp']</value>
      <webElementGuid>f6d4772d-3df9-4221-a1b4-799b707ef1f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
