<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Shan Koe Mee_full-width</name>
   <tag></tag>
   <elementGuidId>cbb07805-afaa-4197-b627-d5152ca7654f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topGameTabs']/div/div[5]/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f7045d98-b883-4339-8040-a53ade2a4245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-width</value>
      <webElementGuid>dbb4b66d-0364-4554-b3db-025301a81fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.santalong.com/background/sport_gamehall.webp</value>
      <webElementGuid>4cd79fde-402e-4d45-8d49-12c87d942f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topGameTabs&quot;)/div[@class=&quot;wrapper-games-tab&quot;]/div[@class=&quot;item-game&quot;]/div[@class=&quot;app-card-wrapper wrapper&quot;]/a[1]/div[@class=&quot;card&quot;]/img[@class=&quot;full-width&quot;]</value>
      <webElementGuid>ffb7325c-0388-41a6-a7e7-4b2e92d89d4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topGameTabs']/div/div[5]/div/a/div/img</value>
      <webElementGuid>852bb57d-bcc0-446a-a15b-40868d06476c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.santalong.com/background/sport_gamehall.webp')]</value>
      <webElementGuid>cb26704e-43f5-499d-aa5c-a96ff47e97c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a/div/img</value>
      <webElementGuid>3e475935-3708-4c45-a45a-56f73814dc24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.santalong.com/background/sport_gamehall.webp']</value>
      <webElementGuid>30403bdb-1525-49b0-b0e2-54024b87607e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
