<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__full-width</name>
   <tag></tag>
   <elementGuidId>f593155d-c929-489b-a104-3cc2c884cd6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topGameTabs']/div/div[3]/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.full-width</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>225a1b4f-9032-4685-b86c-089a5086d8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-width</value>
      <webElementGuid>bc11c858-7184-4deb-8c0d-21dc8a9adf93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.santalong.com/background/casino_shortcut.webp</value>
      <webElementGuid>7ad46938-5b15-4a3e-890d-256996cfaa8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topGameTabs&quot;)/div[@class=&quot;wrapper-games-tab&quot;]/div[@class=&quot;item-game&quot;]/div[@class=&quot;app-card-wrapper wrapper&quot;]/a[1]/div[@class=&quot;card&quot;]/img[@class=&quot;full-width&quot;]</value>
      <webElementGuid>3fed4cc8-4ba7-4fbb-99b8-551fb9ca0df6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topGameTabs']/div/div[3]/div/a/div/img</value>
      <webElementGuid>73e6400c-d899-4858-b60f-d8d9fd14dd86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.santalong.com/background/casino_shortcut.webp')]</value>
      <webElementGuid>4297b3c6-3730-47e9-b70e-9f4c22f3f5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/div/img</value>
      <webElementGuid>a9e36d31-7252-466e-b1d6-bccd2eef420f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.santalong.com/background/casino_shortcut.webp']</value>
      <webElementGuid>04c77220-b6d1-4df6-9f14-af3b6d899f73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
