<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__captcha</name>
   <tag></tag>
   <elementGuidId>af667e7b-eb31-4f95-8c0e-33528a1a3a51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login_captcha']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login_captcha</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>735423a8-38a9-4045-89f3-27ebef12d222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_captcha</value>
      <webElementGuid>991706b8-ea29-4cbe-be95-beef87505a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>17bbcc8e-0cde-4d59-840d-2ac2c6789883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>captcha</value>
      <webElementGuid>aced70aa-e68b-407c-99f0-fd9ada572f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Captcha</value>
      <webElementGuid>1487211c-cbf9-4f45-85a9-8fe8ff9fd3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>user.captcha</value>
      <webElementGuid>4579a927-0746-4042-a133-f8721f945526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>^[0-9]{0,}$</value>
      <webElementGuid>74300a08-a851-4fc6-820e-9e11d27c7a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>6b4ef8ff-f470-4944-8651-41c640861097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>13df5ad1-a207-4931-9145-b8c43e228cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>db9ff7ef-d794-4bc9-89ca-5bb90fbd53e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern-restrict</name>
      <type>Main</type>
      <value>^[0-9]{0,}$</value>
      <webElementGuid>7d2e8474-f60a-4f4e-8e33-974cfe33e66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-valid-pattern ng-valid-maxlength ng-valid ng-valid-required</value>
      <webElementGuid>50b48b62-a6e0-4df5-bf33-b093d4983569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_captcha&quot;)</value>
      <webElementGuid>f04b1232-fa44-4b31-9be8-31dbae318a90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login_captcha']</value>
      <webElementGuid>f6a4f463-f5d4-483c-8263-f2b0475b5220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div/div[3]/div[3]/div/div/input</value>
      <webElementGuid>c26ded3e-b8e0-4a24-83f5-b01614e84824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/input</value>
      <webElementGuid>fffa0407-4aa3-45b5-920f-e7dbf0b26010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login_captcha' and @type = 'tel' and @name = 'captcha' and @placeholder = 'Input Captcha']</value>
      <webElementGuid>d5460d89-b479-4114-b9b6-a1ddc79416cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
