<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>db0536d5-2c68-40d4-8432-3963710932bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-main.main-register</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b01493c1-4e1f-4af1-8aa9-d624365f71e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-main main-register</value>
      <webElementGuid>cc814210-f051-4ba0-ab64-814ee8c1289b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/register</value>
      <webElementGuid>d9b66f64-cde6-4ea3-8beb-7c7b75de7339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3bb6ecac-4eba-4a79-af59-9e4ccf7dc237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>42447e60-23c0-4b76-b680-e9f1d5c2c520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>စာရင္းသြင္းရန္</value>
      <webElementGuid>e31ec1f5-0232-40e4-936f-4f7043f7103b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topLayer&quot;)/div[@class=&quot;side-menu text-center&quot;]/div[@class=&quot;group-btn-login&quot;]/div[@class=&quot;logged-in text-center&quot;]/a[@class=&quot;btn btn-main main-register&quot;]</value>
      <webElementGuid>c3d46dbc-cc17-42a2-8023-3a41226e83fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@type='button']</value>
      <webElementGuid>bcef28ba-80c9-472d-a3f5-ce1329f095dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topLayer']/div/div/div[2]/a</value>
      <webElementGuid>2764dd33-02b3-45a4-b1e3-afbd4e351259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'စာရင္းသြင္းရန္')]</value>
      <webElementGuid>3aa4ab92-65d1-4b53-8dda-c6c366a77bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ေလာ့အင္'])[1]/following::a[1]</value>
      <webElementGuid>fe53f4f4-5098-449a-86ce-7604cc1c1085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='စေလာ့ဒ္ဂိမ္း'])[1]/preceding::a[1]</value>
      <webElementGuid>798ce169-f286-4247-845d-12898be34dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ဗီဒီယိုဂိမ်းများ'])[1]/preceding::a[2]</value>
      <webElementGuid>b38dbd01-aa02-40d2-8df7-0331879a5545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='စာရင္းသြင္းရန္']/parent::*</value>
      <webElementGuid>4440efc2-827f-45be-b82b-fff80263b29a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/register')]</value>
      <webElementGuid>89fdb92a-597b-4632-a8df-a3d39234c74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/a</value>
      <webElementGuid>b78263db-6725-4664-9bca-79e2bfae8f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/register' and @type = 'button' and (text() = 'စာရင္းသြင္းရန္' or . = 'စာရင္းသြင္းရန္')]</value>
      <webElementGuid>6169cfc0-a505-48a8-868a-4e9339348edf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
