<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>439d0a9a-7727-4078-b470-2af92045bf28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button.ng-binding.button-positive.activated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Username - nct002'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c66cd1b-fcbd-4723-8a83-0f5ce145301c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>button in buttons</value>
      <webElementGuid>d52fc60b-bbf6-482d-b674-e28409e6c49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$buttonTapped(button, $event)</value>
      <webElementGuid>970497cf-7c0e-475e-a234-45c881755eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button ng-binding button-positive activated</value>
      <webElementGuid>d2bf8f54-4933-47bb-aba0-f19288b65f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>button.type || 'button-default'</value>
      <webElementGuid>3f69dfe5-c65a-41f1-b60b-444300f4e9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>button.text</value>
      <webElementGuid>d4670f78-3160-4332-93a1-db1db605dd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>5a32d3b1-9d34-47e9-93e0-a89adeadcace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;platform-ios content-only desktop grade-a platform-browser platform-win32 platform-ready popup-open&quot;]/div[@class=&quot;popup-container v2-theme-popup undefined popup-showing popup-hidden&quot;]/div[@class=&quot;popup&quot;]/div[@class=&quot;popup-buttons&quot;]/button[@class=&quot;button ng-binding button-positive activated&quot;]</value>
      <webElementGuid>a8a15508-d705-4f47-9bc9-834bcbede6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/register/Page_YG168  Best Online Casino In Myanmar/iframe__registerFrame</value>
      <webElementGuid>d51a4c57-6821-42b9-be10-629d0e51cc79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username - nct002'])[1]/following::button[1]</value>
      <webElementGuid>88948593-83bb-4bd5-a8c9-829a635ce077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register Success'])[1]/following::button[1]</value>
      <webElementGuid>d948e4cd-36bc-43e7-8461-4c1bf132483a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>11817079-43d5-4273-aaaa-4776925dac33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>3fb3fdb9-ff87-46f7-8e28-3478a1887c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>6d6a9bf9-de87-489c-9a4e-b9c721f1fe75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
