<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__registerFrame</name>
   <tag></tag>
   <elementGuidId>71897383-5ca5-4ec3-b0ca-0ce134f1cf5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registerFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='registerFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4fd420f4-2b87-4e9a-8157-b16e6b65fec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerFrame</value>
      <webElementGuid>28e706bf-961e-49fd-9b93-cb9839ebc8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/app?content_only=1&amp;lang=mm#/register</value>
      <webElementGuid>340ffcff-07c5-4b64-91db-24767f853b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-height</value>
      <webElementGuid>5f806f48-1219-4584-9f41-415698a19fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8cdf433b-9255-4a26-819c-3a7e35bb49cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerFrame&quot;)</value>
      <webElementGuid>c6b9a670-20f5-40a6-98d2-0a91036e9d47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='registerFrame']</value>
      <webElementGuid>14d96d12-0920-4c6c-b35f-3db0d25d8ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/iframe</value>
      <webElementGuid>06b3ad31-6a75-4670-b98f-14420ee471c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>be658487-0dc7-4a2c-9ca5-f59fdde4b8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'registerFrame' and @src = '/app?content_only=1&amp;lang=mm#/register']</value>
      <webElementGuid>736a3913-1e6d-45d3-9108-745424536279</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
