<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__confirm_password</name>
   <tag></tag>
   <elementGuidId>76b9a47d-f5ac-4032-a231-f664cb4b7dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;confirm_password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='confirm_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98df4ed7-118f-4cb1-8d88-2541919a2ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1769cc2d-9e22-4d80-8b77-caa6f168afae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-box input-lg full-width ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-pattern ng-valid-maxlength ng-not-empty-add ng-pristine-remove ng-dirty-add ng-valid-parse-add ng-valid-add ng-invalid-remove ng-valid-required-add ng-invalid-required-remove ng-animate ng-empty-remove</value>
      <webElementGuid>22a54e50-c2ce-4c49-a4e7-585ff55fb7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm_password</value>
      <webElementGuid>940c0af1-d2f4-4027-9148-8eb34df5fc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ff94fcd0-51dc-4213-ba7d-b6b4fe031efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>_registerConfig.password.enabled</value>
      <webElementGuid>541eddba-4e73-47f9-adf6-acc255e4accf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>pwdCheckFocus.confirmPassword = true</value>
      <webElementGuid>bd7acf01-344d-437f-a5c0-223fd9093d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>pwdCheckFocus.confirmPassword = false</value>
      <webElementGuid>9d3cb9d3-3506-46b5-b319-04729b7e3d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5c27f083-e8e4-41a3-b026-1488405e38b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>dataRegister.confirm_password</value>
      <webElementGuid>ca5872f0-b95a-457a-85ac-a1701d554681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>စကားဝွက္ အတည္ၿပဳပါ</value>
      <webElementGuid>ebb69ce4-1674-4303-99e3-1cdf864e5dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^[A-Za-z0-9]*$/</value>
      <webElementGuid>47108534-d0b4-4709-a465-56fab9ad69d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>checkPwdConfirm()</value>
      <webElementGuid>b6b229eb-67c0-44fd-be4e-7739ee9d35bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern-restrict</name>
      <type>Main</type>
      <value>^[0-9a-zA-Z]*$</value>
      <webElementGuid>7a3a8367-77cf-48f0-81e1-8f13ee82044f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>79a1958d-682b-49ac-a767-86d386e0f07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>checkOtpTime</value>
      <webElementGuid>d37dbb0f-875a-4ba4-8ac6-64531b06af8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'disable' : checkOtpTime }</value>
      <webElementGuid>db4f6997-0e65-4233-8264-c3234ac7121b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a73fed4b-2d38-4d6f-b80e-5b8e9c538c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register-mobile&quot;)/div[@class=&quot;register-wrapper&quot;]/form[@class=&quot;ok-yg ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-minlength ng-dirty ng-valid-parse ng-valid-pattern&quot;]/div[@class=&quot;row&quot;]/input[@class=&quot;input-box input-lg full-width ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-pattern ng-valid-maxlength ng-not-empty-add ng-pristine-remove ng-dirty-add ng-valid-parse-add ng-valid-add ng-invalid-remove ng-valid-required-add ng-invalid-required-remove ng-animate ng-empty-remove&quot;]</value>
      <webElementGuid>6ae1913d-0037-4538-8fb3-51f61c5dd385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/register/Page_YG168  Best Online Casino In Myanmar/iframe__registerFrame</value>
      <webElementGuid>4ec3a13b-6c4e-461e-b883-f87b30e5f1b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='confirm_password']</value>
      <webElementGuid>9c991eab-20a4-45e1-b942-e5e31b6d0bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register-mobile']/div/form/div[3]/input</value>
      <webElementGuid>37d046f7-9edd-44f6-8398-b23339516b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>0c9e33bd-09dd-4321-9a03-9f93e05a1aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirm_password' and @placeholder = 'စကားဝွက္ အတည္ၿပဳပါ']</value>
      <webElementGuid>15804d44-638c-4ebe-b747-4c1c7e63b407</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
