<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__full_name</name>
   <tag></tag>
   <elementGuidId>9ec06e03-2d0a-4bf3-986a-12ffe524fe49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#full_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='full_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb07115a-d633-430f-82bc-ab9e311d299e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>24e3ab99-3f40-4eb1-95b4-5ebb8aefad8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-box input-lg full-width ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-pattern ng-valid-maxlength ng-not-empty-add ng-pristine-remove ng-dirty-add ng-valid-parse-add ng-valid-add ng-invalid-remove ng-valid-required-add ng-invalid-required-remove ng-animate ng-empty-remove</value>
      <webElementGuid>32202d38-ba5b-4071-acd1-b85dcec6c413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>full_name</value>
      <webElementGuid>cea7b2ed-455f-4c53-8666-533005c411e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>full_name</value>
      <webElementGuid>1371272f-1770-4014-aeff-f6eb78418e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>df3917a0-cefc-43e7-85e9-59f44fd501c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>dataRegister.full_name</value>
      <webElementGuid>351764fc-85a1-4133-8579-dd7d115ccc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ec2d9956-ca82-4322-a247-e0bff78e2385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>inFocuscheckFullName()</value>
      <webElementGuid>4b7cb088-e48f-4696-8667-c05d2052c8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>outFocuscheckFullName()</value>
      <webElementGuid>a36c0d3e-d682-4bf1-b506-81e249e1d236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>^[^`~!@#$%^&amp;*()_+={}​\[\]|\\:;“’&lt;,>.?๐฿​'&quot;-0123456789]*$</value>
      <webElementGuid>6e987bcb-53aa-492d-8177-973e4390a9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern-restrict</name>
      <type>Main</type>
      <value>^[^`0123456789~!@#$%^&amp;*()_+={}​\[\]|\\:;“’&lt;,>.?๐฿​'&quot;-]*$</value>
      <webElementGuid>7bdae2bc-7256-4ea6-8a3e-528a70121b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>9a23ac34-5f84-4337-89c7-4ebb815eff03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e0cb509d-608d-436d-8297-48c4b2217123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>အမည္ရင္း</value>
      <webElementGuid>f6d53d89-dc0e-4e35-9d91-e23708d72b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>checkOtpTime</value>
      <webElementGuid>5ce20f2b-25b1-443a-8f76-bd2b59c5e422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'disable' : checkOtpTime }</value>
      <webElementGuid>b88926a9-37b5-4c99-a85b-4a40403d462d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1f918fb0-c690-4ae3-9703-935655190cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;full_name&quot;)</value>
      <webElementGuid>76aaf2e4-8652-4a3a-a1f6-8cafbf0f0376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/register/Page_YG168  Best Online Casino In Myanmar/iframe__registerFrame</value>
      <webElementGuid>6cbf4c53-6371-4124-adab-f4d5b04cfa2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='full_name']</value>
      <webElementGuid>f03509a8-4a0f-4e27-8dae-3f80aef1224c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register-mobile']/div/form/div[4]/input</value>
      <webElementGuid>b6ae8253-6532-450b-bd75-fb690450ef55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>ffa158ca-b937-4b24-9846-35948bfe36f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'full_name' and @name = 'full_name' and @placeholder = 'အမည္ရင္း']</value>
      <webElementGuid>3f9f6def-7e18-48f2-9ba7-61469d892fef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
