<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CQ9_1_2</name>
   <tag></tag>
   <elementGuidId>7a9bf57a-0854-4ea8-beb2-949e46e9d3c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5421ea6d-0bf9-4494-8642-d880b9bafccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a67a256e-949a-4545-a85b-317b1ef2a822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>sort in sortCasino | orderBy:'order'</value>
      <webElementGuid>8586fd9a-50a5-4a83-8911-e9da04b0326d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'active': sort.tab }</value>
      <webElementGuid>1028d20d-6974-446c-8eeb-853c43c78e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>39025b9b-732a-4a99-bd9f-7fd7dad32224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>gamesConsoleManager.activeSubTabLiveCasino(sort.name)</value>
      <webElementGuid>6d1f0e95-50f8-4f5a-90b1-79117a4b22bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>sort.enabled</value>
      <webElementGuid>7a35210c-ee69-4eee-af13-7be61c8716ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-scroll-to</name>
      <type>Main</type>
      <value>.game-tabs-container</value>
      <webElementGuid>e5c765c7-da89-4509-9006-aa5bb4776995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding ng-scope</value>
      <webElementGuid>f91252a0-b6fc-4029-87fa-c50cbe9a62d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e84454c6-2b5f-47b1-bcc8-487923fa47e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         
                    
                        CQ9
                </value>
      <webElementGuid>717342a8-69d4-4563-8e94-8e28646d39ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-games-tabs&quot;)/div[@class=&quot;game-tabs-container&quot;]/div[@class=&quot;tab-content&quot;]/div[@id=&quot;live-casino-game&quot;]/div[@id=&quot;live-casino-game&quot;]/div[@class=&quot;col-xs-12 no-padding live-casino-bg&quot;]/div[@class=&quot;container-layout-game&quot;]/div[@class=&quot;tab-select-game-hall&quot;]/button[@class=&quot;ng-binding ng-scope&quot;]</value>
      <webElementGuid>8b784306-5fdb-4b6e-8a4a-140ba655b133</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
      <webElementGuid>e43ad0ce-fcb7-4622-95b1-7275c580e948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='live-casino-game']/div/div/div/button[2]</value>
      <webElementGuid>2adbec38-14d4-49e3-8cd4-1ceddb0700b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Black Jack'])[1]/following::button[2]</value>
      <webElementGuid>27166f28-7e63-4e51-94ed-e99fd88dfe4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/div/div/button[2]</value>
      <webElementGuid>46b88dc5-72b1-45bc-ae7e-cf37759b2448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                         
                    
                        CQ9
                ' or . = '
                         
                    
                        CQ9
                ')]</value>
      <webElementGuid>bc4d628f-a94e-40c0-9b5b-ed8302e154a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
