<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>5c077627-6a28-4f9a-97f2-335af16c64e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu-video-game-icon']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-video-game-icon > div.card > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c0d76e14-4baf-4e7e-8515-b2d0a8f88e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.santalong.com/background/fish_gamehall.webp</value>
      <webElementGuid>4380e710-8861-48fc-8fb3-ca1f3bb989c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-video-game-icon&quot;)/div[@class=&quot;card&quot;]/img[1]</value>
      <webElementGuid>90c5e35b-d658-4b4a-8b6b-0c896fa6fdc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menu-video-game-icon']/div/img</value>
      <webElementGuid>a43ae5c0-8160-4aae-81ed-8e9eb6e6ff75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.santalong.com/background/fish_gamehall.webp')]</value>
      <webElementGuid>3de70a7b-24a8-4ab1-91ab-3ed04724b446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/div/img</value>
      <webElementGuid>97126c73-4f25-413d-935e-0ca2764a7abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.santalong.com/background/fish_gamehall.webp']</value>
      <webElementGuid>43f63f4c-3f1a-4a62-9aca-8bad9ac6abf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
