<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_live_full-width</name>
   <tag></tag>
   <elementGuidId>4093499e-3932-4a1e-b025-90867a35e633</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topGameTabs']/div/div[4]/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.item-game.poker > div.app-card-wrapper.wrapper > a > div.card > img.full-width</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8cc5f7b6-122e-4f06-9925-120f430b1674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-width</value>
      <webElementGuid>e78f929f-6bca-4c2e-a15c-e309e5ed1c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.santalong.com/background/pk89_gamehall.webp</value>
      <webElementGuid>6dfcd6d6-8ef9-4326-beda-300139e28519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topGameTabs&quot;)/div[@class=&quot;wrapper-games-tab&quot;]/div[@class=&quot;item-game poker&quot;]/div[@class=&quot;app-card-wrapper wrapper&quot;]/a[1]/div[@class=&quot;card&quot;]/img[@class=&quot;full-width&quot;]</value>
      <webElementGuid>4004a891-ac86-4b8b-aced-482ca544977d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topGameTabs']/div/div[4]/div/a/div/img</value>
      <webElementGuid>fc65202c-590d-47dc-a21c-298adb86072c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.santalong.com/background/pk89_gamehall.webp')]</value>
      <webElementGuid>604d9a0e-3b7e-43d9-9eb9-fe72c5a3343a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a/div/img</value>
      <webElementGuid>bd071081-1c2d-4197-ace2-24061716128f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.santalong.com/background/pk89_gamehall.webp']</value>
      <webElementGuid>c6c0c1e7-afce-4a1d-a737-01f8d7100d77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
