<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Shan Koe Mee_full-width</name>
   <tag></tag>
   <elementGuidId>5ba6da17-4ff9-4982-abb6-b1bf67176f20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topGameTabs']/div/div[5]/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>43429977-154c-4f3d-8850-19cb3ab4ea6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-width</value>
      <webElementGuid>d0c3df7c-a7bb-4ded-9a19-da4bf65980f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.santalong.com/background/sport_gamehall.webp</value>
      <webElementGuid>0ca8574c-4cd0-40d6-a31b-4aa736b183e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topGameTabs&quot;)/div[@class=&quot;wrapper-games-tab&quot;]/div[@class=&quot;item-game&quot;]/div[@class=&quot;app-card-wrapper wrapper&quot;]/a[1]/div[@class=&quot;card&quot;]/img[@class=&quot;full-width&quot;]</value>
      <webElementGuid>c4b904d6-d0db-4f23-98df-434c353c50aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topGameTabs']/div/div[5]/div/a/div/img</value>
      <webElementGuid>eca3ca79-c804-4d66-bc47-32e04db3f055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.santalong.com/background/sport_gamehall.webp')]</value>
      <webElementGuid>c1cee039-a0d2-4e7a-a8f7-e1a84e39b219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a/div/img</value>
      <webElementGuid>56dc1fa0-0a71-47bc-b165-4333589e20fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.santalong.com/background/sport_gamehall.webp']</value>
      <webElementGuid>0a4598b0-c2ed-4782-8b75-482a1654c471</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
