<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>b2ee9a78-2028-407c-88cf-6144f733951e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topLayer']/div/div[3]/div[8]/a/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eb7f2671-be72-49d6-a044-8a57e812d8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                အမွတ္စဥ္မ်ား</value>
      <webElementGuid>d01b906e-c484-4b50-892b-594208a22631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topLayer&quot;)/div[@class=&quot;side-menu text-center&quot;]/div[@class=&quot;game-group&quot;]/div[@class=&quot;text-center to-game&quot;]/a[@class=&quot;btn btn-game btn-1&quot;]/div[@class=&quot;info&quot;]/div[@class=&quot;btn-msg&quot;]/span[1]</value>
      <webElementGuid>09385771-eac5-4775-bbe1-d27822554fb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topLayer']/div/div[3]/div[8]/a/div/div[2]/span</value>
      <webElementGuid>d254f2ee-1c60-4de1-87cc-c15ed1223426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ပရိုမိုးရွင္း'])[1]/following::span[1]</value>
      <webElementGuid>719dbfe8-060e-46e8-99a1-f101fe80ee29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installation'])[1]/following::span[2]</value>
      <webElementGuid>2a4184d1-a456-4f1f-b77b-bf799edc5349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ေဒါင္းလုဒ္'])[1]/preceding::span[1]</value>
      <webElementGuid>4f2e8fb7-401b-4471-a743-883a821b5553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ကြ ်နု္ပ္တုိိ ့အေၾကာင္း'])[1]/preceding::span[1]</value>
      <webElementGuid>7edc3941-cff0-4131-aabb-146cc7335bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='အမွတ္စဥ္မ်ား']/parent::*</value>
      <webElementGuid>32a92de3-fd0a-42bc-a039-d90fde711df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/a/div/div[2]/span</value>
      <webElementGuid>f9eb0b0b-4f08-4160-8711-29c73b896f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                                                အမွတ္စဥ္မ်ား' or . = '
                                                အမွတ္စဥ္မ်ား')]</value>
      <webElementGuid>71482e43-4cdc-4b3d-9b53-0960d715e07d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
